MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
#KEY_OVERRIDE_ENABLE = yes
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

INTROSPECTION_KEYMAP_C = keymap_tuxmaniac.c

ifeq ($(strip $(KLUDGE_THUMBCOMBOS)),yes)
  COMBO_ENABLE = yes
  OPT_DEFS += -DKLUDGE_THUMBCOMBOS
endif
